/**
 * key manager microservice
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Api token dto
 */
export interface ApiTokenDto { 
    /**
     * Signed jwt token
     */
    api_token: string;
}

