/**
 * key manager microservice
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiTokenDto } from './apiTokenDto';


/**
 * List of api tokens
 */
export interface GetApiTokensResponse { 
    /**
     * Signed jwt token
     */
    tokens?: Array<ApiTokenDto>;
}

